services:
  app:
    container_name: app
    build:
      context: ./app/
      dockerfile: DockerFile
    ports:
      - 5173:5173
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: db
    image: postgis/postgis:12-3.4-alpine
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pcahuzac -d collections"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: DockerFile
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    tty: true
    env_file:
      - .env
    depends_on:
      - db

  studio:
    container_name: studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    ports:
      - 5555:5555
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  # nginx:
  #   image: nginx
  #   volumes:
  #      - ./nginx/local.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
  #     - app
  #     - studio
  #     - db
