services:
  app:
    build:
      context: ./app/
      dockerfile: DockerFile
    
    ports:
      - 5173:5173
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    
  db:
    image: postgis/postgis:12-3.4-alpine
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./api/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pcahuzac -d collections"]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api/
      dockerfile: DockerFile
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    tty: true
    env_file:
      - .env
    depends_on:
      - db

  studio:
    container_name: studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    ports:
      - 5555:5555
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
