FROM node:current-alpine3.20
WORKDIR /usr/src/api


COPY package*.json ./

RUN npm i

COPY . .

EXPOSE 3000

RUN npm i -g pnpm

RUN npx prisma generate

CMD ["npm", "run", "watch", "--host", "0.0.0.0"]