FROM node:current-alpine3.20

WORKDIR /usr/src/api

COPY package*.json ./

RUN npm i

COPY . .

# RUN npm i @prisma/cli

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev", "--host", "0.0.0.0"]

